apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
  name: grpc-web-test-envoy
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/launch-stage: ALPHA
    spec:
      containerConcurrency: 250
      containers:
        - image: europe-west1-docker.pkg.dev/com-ridedott-test/grpc-web-test/envoy:1.0.0
          ports:
            - containerPort: 8080
              name: h2c
          resources:
            limits:
              cpu: '1'
              memory: 256Mi
      timeoutSeconds: 30
  traffic:
    - latestRevision: true
      percent: 100
